apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:

      volumes:
        - name: config
          iscsi:
            targetPortal: {{ .Values.diskstation.ip_address }}
            iqn: {{ .Values.sonarr.iqn }}
            lun: 1
            fsType: ext4
            readOnly: false
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime

      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: nas
              mountPath: /mnt/nas
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 8989
