---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:

      volumes:
      - name: data
        iscsi:
          targetPortal: {{ .Values.diskstation.ip_address }}
          iqn: {{ .Values.registry.iqn }}
          lun: 1
          fsType: ext4
          readOnly: false

      containers:
        - image: registry:2
          name: registry
            
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry

          ports:
            - containerPort: 5000
