apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.nginx.ip_address }}
spec:
  type: LoadBalancer
  selector:
    name: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80