apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    name: nginx
  ports:
    - name: https
      port: 443
      targetPort: 443