apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: plex
      port: 32400
      targetPort: 32400
      nodePort: 32400