apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  labels:
    app: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:

      nodeSelector:
        kubernetes.io/arch: amd64

      volumes:
        - name: vpn-config
          configMap:
            name: openvpn
        - name: vpn-secret
          secret:
            secretName: openvpn
        - name: dev-net
          emptyDir: {}
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config
          configMap:
            name: nzbget

      initContainers:
        - name: config
          image: alpine
          volumeMounts:
            - name: nas
              mountPath: /mnt/nas
            - name: config
              mountPath: /nzbget.conf
              subPath: nzbget.conf
          command:
            - /bin/sh
            - -c
            - |-
              set -e
              if [ ! -f /mnt/nas/nzbget/nzbget.conf ]; then
                cp /nzbget.conf /mnt/nas/nzbget/nzbget.conf
              fi

      containers:

        - name: openvpn
          image: cjbottaro/openvpn:latest
          args:
            - --config
            - /etc/vpn.ovpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: vpn-config
              mountPath: /etc/vpn.ovpn
              subPath: vpn.ovpn
            - name: vpn-secret
              mountPath: /etc/vpn.auth
              subPath: vpn.auth
            - name: dev-net
              mountPath: /dev/net

        - name: nzbget
          image: cjbottaro/nzbget:latest
          command:
            - ./nzbget
            - -s
            - -c
            - /mnt/nas/nzbget/nzbget.conf
          volumeMounts:
            - name: dev-net
              mountPath: /dev/net
            - name: nas
              mountPath: /mnt/nas
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 6789
