apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  labels:
    app: nzbget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:

      volumes:
        - name: wireguard
          configMap:
            name: wireguard
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config
          configMap:
            name: nzbget

      initContainers:
        - name: wireguard
          image: cjbottaro/wireguard
          imagePullPolicy: Always
          command:
            - wg-quick
            - up
            - vpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: wireguard
              mountPath: /etc/wireguard/vpn.conf
              subPath: vpn.conf

      containers:
        - name: nzbget
          image: linuxserver/nzbget
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /nzbget/nzbget.conf
              subPath: nzbget.conf
            - name: nas
              mountPath: /nzbget/downloads
              subPath: nzbget
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 6789
