apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  labels:
    app: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:

      nodeSelector:
        kubernetes.io/arch: amd64

      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4

      volumes:
        - name: vpn-config
          configMap:
            name: openvpn
        - name: vpn-secret
          secret:
            secretName: openvpn
        - name: dev-net
          emptyDir: {}
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config
          configMap:
            name: nzbget

      containers:

        - name: openvpn
          image: cjbottaro/openvpn:latest
          args:
            - --config
            - /etc/vpn.ovpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: vpn-config
              mountPath: /etc/vpn.ovpn
              subPath: vpn.ovpn
            - name: vpn-secret
              mountPath: /etc/vpn.auth
              subPath: vpn.auth
            - name: dev-net
              mountPath: /dev/net

        - name: nzbget
          image: cjbottaro/nzbget:latest
          imagePullPolicy: Always
          command:
            - ./nzbget
            - -s
            - -c
            - nzbget.conf
          volumeMounts:
            - name: dev-net
              mountPath: /dev/net
            - name: config
              mountPath: /nzbget/nzbget.conf
              subPath: nzbget.conf
            - name: nas
              mountPath: /nzbget/downloads
              subPath: nzbget
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 6789
