version: "3"

services:

  alpine-glibc:
    image: cjbottaro/alpine-glibc:3.7
    build:
      context: alpine
      args:
        ALPINE_VERSION: 3.7
        GLIBC_VERSION: 2.27-r0

  openvpn:
    image: cjbottaro/openvpn:latest
    build:
      context: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dallas.ovpn:/etc/vpn.ovpn
      - ./auth.txt:/etc/vpn.auth
    command: ["--config", "/etc/vpn.ovpn"]

  certificates:
    image: cjbottaro/certificates
    build:
      context: certificates
    volumes:
      - ./secrets:/secrets
    command:
      - certonly
      - --non-interactive
      - --agree-tos
      - -m cjbottaro@alumni.utexas.net
      - --dns-dnsimple
      - --dns-dnsimple-credentials=/secrets/dnsimple.ini
      - -d nutrition.cjbotta.ro
      - -d radarr.cjbotta.ro

  radarr:
    image: cjbottaro/radarr:0.2.0.995
    build:
      context: radarr
      args:
        RADARR_VERSION: 0.2.0.995
