version: "3"

services:

  openvpn:
    image: cjbottaro/openvpn:latest
    build:
      context: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dallas.ovpn:/etc/vpn.ovpn
      - ./auth.txt:/etc/vpn.auth
    command: ["--config", "/etc/vpn.ovpn"]

  certificates:
    image: cjbottaro/certificates
    build:
      context: certificates/build

  rsync:
    image: cjbottaro/rsync
    build:
      context: rsync