version: "3"

services:

  openvpn:
    image: cjbottaro/openvpn:latest
    build:
      context: openvpn/build
      args:
        ALPINE_VERSION: 3.14

  nzbget:
    image: cjbottaro/nzbget:latest
    build:
      context: nzbget/build
      args:
        ALPINE_VERSION: 3.14
        NZBGET_RELEASE: https://github.com/nzbget/nzbget/releases/download/v21.2-r2333/nzbget-21.2-testing-r2333-bin-linux.run

  certificates:
    image: cjbottaro/certificates
    build:
      context: certificates/build

  wireguard:
    image: cjbottaro/wireguard:latest
    build:
      context: wireguard

  postgres:
    image: registry.cjbotta.ro/postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432
    build:
      context: postgres
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}