apiVersion: v1
kind: Pod
metadata:
  name: temp
spec:
  
  nodeSelector:
    kubernetes.io/hostname: pineview

  serviceAccountName: certificates

  volumes:
    - name: secrets
      secret:
        secretName: certificates
    - name: files
      configMap:
        name: certificates

  containers:
    - name: certs
      image: cjbottaro/certificates
      command:
        - sleep
        - "1000000"
      env:
        - name: DNSimple_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: certificates
              key: dnsimple_token
      volumeMounts:
        - name: secrets
          mountPath: /etc/dnsimple.ini
          subPath: dnsimple.ini
        - name: files
          mountPath: /run.sh
          subPath: run.sh
