apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:

      volumes:
        - name: wireguard
          configMap:
            name: wireguard
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd
        - name: localtime
          hostPath:
            path: /etc/localtime

      initContainers:
        - name: wireguard
          image: cjbottaro/wireguard
          securityContext:
            privileged: true
          command: ["wg-quick", "up", "vpn"]
          volumeMounts:
            - name: wireguard
              mountPath: /etc/wireguard

      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: nas
              mountPath: /mnt/nas
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 8080
