apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr

    spec:

      # nodeSelector:
      #   kubernetes.io/hostname: pineview

      volumes:
        - name: app-data
          iscsi:
            targetPortal: 192.168.1.113
            iqn: iqn.2000-01.com.synology:diskstation.Target-1.77d659b9be
            lun: 1
            fsType: ext4
            
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
            
        - name: localtime
          hostPath:
            path: /etc/localtime

      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0" # It's a container, just fucking run as root.
          volumeMounts:
            - name: app-data
              mountPath: /config
            - name: nas
              mountPath: /mnt/nas
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 8989
