apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:

      nodeSelector:
        kubernetes.io/hostname: pineview

      volumes:
        - name: config
          hostPath:
            path: /var/lib/radarr
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime

      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0" # It's a container, just fucking run as root.
          # The way I think downloads work is...
          # radarr: "Hey nzbget, download this movie."
          # nzbget: "Hey radarr, I downloaded this movie at /mnt/nas/nzbget/completed/this_movie."
          # radarr: "Ok, I'm moving /mnt/nas/nzbget/completed/this_movie to /movies"
          # In other words, they assume they are using the same file system.
          volumeMounts:
            - name: config
              mountPath: /config
            - name: nas
              mountPath: /movies
              subPath: movies
            - name: localtime
              mountPath: /etc/localtime
            - name: nas
              mountPath: /mnt/nas
          ports:
            - containerPort: 7878
