apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:

      volumes:
        - name: media
          hostPath:
            path: /mnt/media
        - name: localtime
          hostPath:
            path: /etc/localtime

      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          imagePullPolicy: Always
          env:
            # It's a container, just fucking run as root.
            - name: PUID
              value: "0"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: media
              mountPath: /config
              subPath: radarr
            - name: media
              mountPath: /movies
              subPath: plex/Movies
            # This has to match how nzbget sees its completed movies dir.
            - name: media
              mountPath: /nzbget/downloads/completed/Movies
              subPath: nzbget/completed/Movies
            # This has to match how deluge sees its completed downloads.
            - name: media
              mountPath: /deluge/downloads
              subPath: deluge/downloads
          ports:
            - containerPort: 7878
