apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  labels:
    app: emby
spec:
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:

      nodeSelector:
        kubernetes.io/hostname: pineview

      volumes:
        - name: media
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: dri
          hostPath:
            path: /dev/dri
            
      containers:
        - name: emby
          image: emby/embyserver
          securityContext:
            privileged: true
          env:
            - name: UID
              value: "0"
            - name: GID
              value: "0"
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: emby
            - name: media
              mountPath: /mnt/media
            - name: localtime
              mountPath: /etc/localtime
            - name: dri
              mountPath: /dev/dri
          ports:
            - containerPort: 8096