---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:

      imagePullSecrets:
        - name: registry.cjbotta.ro

      containers:
        - name: chat

          image: registry.cjbotta.ro/chat-release
          imagePullPolicy: Always

          env:
            - name: PHX_SERVER
              value: "true"

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD

            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: chat
                  key: SECRET_KEY_BASE

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chat
                  key: OPENAI_API_KEY

            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chat
                  key: ELEVENLABS_API_KEY

            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: chat
                  key: GOOGLE_OAUTH_CLIENT_ID

            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat
                  key: GOOGLE_OAUTH_CLIENT_SECRET

            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: ACCESS_KEY_ID
                  
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: SECRET_ACCESS_KEY
            
          ports:
            - containerPort: 4000
