---
apiVersion: v1
kind: Secret
metadata:
  name: chat
type: Opaque
data:
  SECRET_KEY_BASE: {{ .Values.chat.secret_key_base | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.chat.openai_api_key | b64enc | quote }}
  ELEVENLABS_API_KEY: {{ .Values.chat.elevenlabs_api_key | b64enc | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.chat.google_oauth.client_id | b64enc | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.chat.google_oauth.client_secret | b64enc | quote }}