apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:

      volumes:
        - name: config
          hostPath:
            path: /var/lib/plex
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media

      nodeSelector:
        kubernetes.io/hostname: pineview

      containers:
        - name: plex
          image: plexinc/pms-docker
          imagePullPolicy: Always
          env:
            - name: TZ
              value: US/Central
            - name: ADVERTISE_IP
              value: http://192.168.1.10,http://plex.cjbotta.ro
          volumeMounts:
            - name: nas
              mountPath: /mnt/nas
            - name: config
              mountPath: /config
          ports:
            - containerPort: 32400