{{- $crontabs := .Values.crontabs -}}
{{ range $name := .Values.names }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: config-sync-{{ $name }}
  labels:
    app: config-sync
spec:
  schedule: {{ index $crontabs $name }}
  successfulJobsHistoryLimit: 1 # Set to 1 or more if you want look at logs of past successful jobs
  concurrencyPolicy: Forbid     # Don't allow more than one of these jobs to run at once
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: config-sync
        spec:
          volumes:
            - name: lib
              hostPath:
                path: /var/lib
            - name: nas
              nfs:
                server: diskstation
                path: /volume1/media

          nodeSelector:
            kubernetes.io/hostname: pineview

          containers:
          - name: config-sync-{{ $name }}
            image: cjbottaro/rsync
            command:
              - rsync
              - -va
              - /mnt/lib/{{ $name }}/
              - /mnt/nas/{{ $name }}
            volumeMounts:
              - name: lib
                mountPath: /mnt/lib
              - name: nas
                mountPath: /mnt/nas

          restartPolicy: OnFailure
{{ end }}