---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:

      volumes:
        - name: pgdata
          iscsi:
            targetPortal: 192.168.1.113
            iqn: iqn.2000-01.com.synology:diskstation.Target-1.efaf369cac9
            lun: 1
            fsType: xfs

      containers:
        - image: postgres:13-alpine
          name: postgres

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data

          ports:
            - containerPort: 5432
