---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:

      volumes:
      - name: data
        iscsi:
          targetPortal: {{ .Values.diskstation.ip_address }}
          iqn: {{ .Values.postgres.iqn }}
          lun: 1
          fsType: ext4
          readOnly: false

      imagePullSecrets:
        - name: registry.cjbotta.ro

      containers:
        - name: postgres

          image: registry.cjbotta.ro/postgres:15.4-alpine
          imagePullPolicy: Always

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql

          ports:
            - containerPort: 5432
