---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: regcreds
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: regcreds
roleRef:
  name: regcreds
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: regcreds

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: regcreds