version: "3"

services:

  openvpn:
    image: cjbottaro/openvpn:latest
    build: .
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dallas.ovpn:/etc/vpn.ovpn
      - ./auth.txt:/etc/vpn.auth
    command: ["--config", "/etc/vpn.ovpn"]
