apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:

      volumes:
        - name: wireguard
          configMap:
            name: wireguard
        - name: config
          persistentVolumeClaim:
            claimName: deluge
        - name: nas
          nfs:
            server: diskstation
            path: /volume1/media
        - name: localtime
          hostPath:
            path: /etc/localtime

      initContainers:
        - name: wireguard
          image: alpine
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - apk add wireguard-tools && wg-quick up vpn
          volumeMounts:
            - name: wireguard
              mountPath: /etc/wireguard

      containers:
        - name: deluge
          image: linuxserver/deluge:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: config
            - name: nas
              mountPath: /mnt/nas
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 8112
